/*
 * Copyright (c) 2024 Provar Limited.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.md file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

export type ErrorCode =
  | 'MISSING_FILE'
  | 'MALFORMED_FILE'
  | 'MISSING_PROPERTY'
  | 'MISSING_PROPERTIES'
  | 'INVALID_VALUES'
  | 'INVALID_VALUE'
  | 'MISSING_VALUE'
  | 'INVALID_FILE_EXTENSION'
  | 'GENERATE_OPERATION_DENIED'
  | 'INVALID_PATH'
  | 'INSUFFICIENT_PERMISSIONS'
  | 'INVALID_ARGUMENT'
  | 'INVALID_PROPERTY'
  | 'UNKNOWN_PROPERTY'
  | 'DOWNLOAD_ERROR'
  | 'GENERIC_ERROR'
  | 'TEST_CASE_NAME'
  | 'COMPILATION_ERROR'
  | 'SETUP_ERROR'
  | 'TEST_RUN_ERROR'
  | 'SF_ERROR'
  | 'MISSING_MANAGER_PACKAGE'
  | 'INVALID_TARGET_ORG'
  | 'MISSING_CONNECTION'
  | 'MISSING_INFORMATION'
  | 'PROJECT_NOT_FOUND'
  | 'INVALID_CONFIGURATION_FILE'
  | 'PROCESSING_ERROR'
  | 'TEST_RUN_NOT_FOUND'
  | 'TEST_RUN_NOT_FINISHED'
  | 'TEST_RUN_FINISHED'
  | 'TEST_RUN_FAILED'
  | 'API_REQUEST_ERROR';

